name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.ts"
      - "**.js"
      - "package.json"
      - "tsconfig.json"
      - "jest.config.*"
      - ".github/workflows/build-and-test.yml"

  push:
    branches:
      - main
    paths:
      - "**.ts"
      - "**.js"
      - "package.json"
      - "tsconfig.json"
      - "jest.config.*"
      - ".github/workflows/build-and-test.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Verify build and test success
        run: echo "✅ Build and tests completed successfully."
